### PR TITLE
Control flow

### PR DESCRIPTION
**Pull request by alexfriesen**
This PR will replaces NgIf, NgFor and NgSwitch with the new Angular Control Flow Syntax.
Also the code is formatted with Prettier.

### CODE REVIEW

**Comment by tonysamperi** [comment]
1) What would be the improvement?
2) I hate prettier.

**Comment by alexfriesen** [comment]
Angulars control flow introduced a lot of performance improvements. Especially @for offers better results than NgFor.

**Comment by tonysamperi** [comment]
Man, performance already improved by being v17. 
I won't introduce unstable syntaxes, because it might improve a bit more.
Let's wait till it's stable at least.
Then I'll do the change.

**Comment by tonysamperi** [comment]
Just for everybody's reference, as for now, from [here](https://angular.io/guide/control_flow):

image

**Pull request closed without merging**
