### PR TITLE
Support for Angular 14

### PR DESCRIPTION
**Pull request by sagrawal31**
* Removed `smp-core-utils` as it was failing with v14 and was not in use in the repo.
* Update browserlist DB by running `npx browserslist --update-db`.
* Rest of the changes were auto made by `ng update @angular/cdk @angular/cli @angular/core @angular/material`

### CODE REVIEW

**Comment by tonysamperi** [comment]
Thanks I'll run the update myself.

**Comment by sagrawal31** [comment]
When can we expect the same?

**Comment by tonysamperi** [comment]
Please have a look at the readme file, thank you.

**Comment by tonysamperi** [comment]
@sagrawal31 published v14, cheers!

**Pull request closed without merging**
