### PR TITLE
feat!: migrate to legacy Angular Material 15 components and styles

### PR DESCRIPTION
**Pull request by LayZeeDK**
# Features
- Update to Angular Material 15 legacy components

# Build
- Add missing direct `tslib` dependency to package
- Update Node.js requirement to the minimum version supported by Angular CLI 15.0
- Migrate to stricter TypeScript compiler options
- Migrate to `@angular-devkit/build-angular:ng-packagr` builder
- Add `@types/prismjs`
- Remove leftover `tsickle` dependency
- Update to compatible `ts-node` version
- Update to Zone.js 0.12.0
- Add `prismjs` to CommonJS allowlist
- Align configurations with fresh Angular CLI 15 workspace
- Migrate to Angular Material 15 themes

# Tests
- Remove leftover duplicate end-to-end testing project
- Migrate Karma and Jasmine dependencies
- Migrate Protractor configuration and tests

# Other information
- Contains commits from the [v14](https://github.com/tonysamperi/ngx-mat-timepicker/tree/v14) branch.
- Contains test improvements from #46.
- MDC-based Angular Material components will requires additional styles.
- Doesn't work with MDC-based global component styles

BREAKING CHANGES
- Require Angular Material 15
- Require Node.js >=14.20.0
- Require the legacy Angular Material global mixins
```scss
@use "@angular/material" as mat;

@include mat.all-legacy-component-typographies();
@include mat.legacy-core();
@include mat.all-legacy-component-themes($my-theme);
```

### CODE REVIEW

**Comment by LayZeeDK** [comment]
Let me know what you think, @tonysamperi.

**Comment by tonysamperi** [comment]
@LayZeeDK again that's extraordinary! Just a couple things I'll need to review before publishing. But we can definitely merge this as well! 
Thanks a lot.
BTW I'll add you to the contributors in the README!

**Comment by tonysamperi** [comment]
@LayZeeDK on a second thought we can't publish using the legacy components, I didn't understand the whole thing yesterday.
I thought it was just scss legacy. Instead you used all the legacy components, meaning I couldn't migrate to new components because it would be a breaking change. 
I need to migrate everything before publishing v15.
What we can do is publish a beta this way...
I'm creating a v15-beta branch alongside the v15 where I'm fixing everything

**Comment by LayZeeDK** [comment]
That's right, changing to MDC-based components would be a breaking change so you have a decision to make.

We are using `ngx-mat-timepicker` at work, that's why I wanted to help migrate to v15. It's going to take some rework of styles to use the MDC-based components though. It was more than what I can contribute right now.

**Comment by tonysamperi** [comment]
@LayZeeDK don't worry, you helped a lot anyway. In fact I started the real migration this morning and I'm almost done...
I just have to fix a few weird behaviours such as this:

image

and it's done 😉

Thanks a lot again!

**Comment by LayZeeDK** [comment]
I looked at that one. This behavior has changed between Angular Material 14 and 15. The mini FAB button doesn't accept an `undefined`/`null`/empty string `color` input value anymore. Instead, it defaults to the `accent` color, causing it to have the `mat-accent` CSS class.

**Comment by tonysamperi** [comment]
@LayZeeDK exactly...I noticed the `defaultColor` in the `CanColor` class...
I'm trying to find in the docs how to control the behaviour or disable the default color...
I will figure it out 🤓

**Comment by LayZeeDK** [comment]
@tonysamperi
As I expect you know, the issue is with our current CSS selector that expect no mat color CSS class for inactive clock face numbers.
```scss
.clock-face {
  [mat-mini-fab]:not(.mat-primary):not(.mat-accent):not(.mat-warn) {
    background: transparent;
  }
}
```

**Comment by tonysamperi** [comment]
@LayZeeDK actually I hadn't got there yet...
But...have this ever worked? Passing undefined was the trick for transparency...
Maybe I don't remember well...I'll try removing that rule from v14 and see what happens :D

**Comment by LayZeeDK** [comment]
@tonysamperi 
Maybe this library should offer legacy components in addition to MDC-based components? Not everyone can migrate to MDC-based Angular Material immediately and that migration is opt-in.

**Comment by tonysamperi** [comment]
@LayZeeDK as I said we can release with different versions...something like `legacy-15.0.0`
otherwise another package name, but that might be confusing being only for v15...
What do you think?

**Comment by LayZeeDK** [comment]
>@LayZeeDK actually I hadn't got there yet...
>But...have this ever worked? Passing undefined was the trick for transparency (theoretically)...
>Maybe I don't remember well...I'll try removing that rule from v14 and see what happens :D
>
>EDIT
>
>Now I remember...the default button is not transparent, that's why we needed that.
@tonysamperi
Exactly, it worked because there was no `mat-primary`, `mat-accent`, or `mat-warn` class but the background was *neutral*, not transparent.

**Comment by LayZeeDK** [comment]
>@LayZeeDK as I said we can release with different versions...something like legacy-15.0.0
otherwise another package name, but that might be confusing being only for v15...
>What do you think?

@tonysamperi 
Angular Material's solution is to have components with the same selectors but using class names such as `MatLegacyButton` with mostly the same API as `MatButton`.

**Comment by tonysamperi** [comment]
@LayZeeDK that was quite clear, but in a practical way how do we allow the double API?
we need a dynamic module importing one of two modules, one importing the defaults, the other importing the legacies?
But still I don't understand how to manage the imports around the app...

Don't tell me I should type everything like `MatButton | MatLegacyButton` 😂😂😂

**Comment by LayZeeDK** [comment]
@tonysamperi
You focus on the MDC migration, I will experiment how to solve this.

**Comment by tonysamperi** [comment]
> We need a duplicate Angular module and duplicate components to do this.
> @tonysamperi You focus on the MDC migration, I will experiment on solving this.

Ok that makes sense, which is more or less like having 2 packages...

But yeah, we could have a `NgxMatTimepickerLegacyModule` and `NgxMatTimepickerModule`...
Who wants the legacy uses the former...
In general I don't like having duplicates and I'm a bit worried about the bundle size...This package was born from a package that made no sense because the guy re-invented the wheel to do things that CDK provides already...

Also your branch basically workes (now in v15)...I would be more inclined to have separate release versions...
That way each bundle is way lighter and it's way faster to work on the code...

But let's think about it...

**Comment by LayZeeDK** [comment]
@tonysamperi 
Okay, so you suggest separate branches with separate releases either through separate package names or version tags?
Option A: `ngx-mat-timepicker-legacy@15.0.0`
Option B: `ngx-mat-timepicker@15.0.0-legacy`

**Comment by tonysamperi** [comment]
> @tonysamperi Okay, so you suggest separate branches with separate releases either through separate package names or version tags? Option A: `ngx-mat-timepicker-legacy@15.0.0` Option B: `ngx-mat-timepicker@15.0.0-legacy`

Yes, with a preference for option B. 
That way people would import everything as they already do and everything would happen under the hood...
The downside is that I don't know how npm would treat `^15.0.0-legacy` when `15.1.0` is out...

**Comment by LayZeeDK** [comment]
@tonysamperi 
That's a valid concern. `^15.0.0-legacy` would probably match `15.1.0`.

**Comment by LayZeeDK** [comment]
Option C is a secondary entry point `ngx-mat-timepicker/legacy`.

**Comment by tonysamperi** [comment]
@LayZeeDK yesterday I finished upgrading all my libs to Angular 15...
And I just tried the `^15.0.0-legacy` thing...

I created a fake lib and published 

- 1.0.0
- 1.0.0-legacy
- 1.1.0
- 1.1.0-legaxy

then created a package with dependency `^1.0.0-legacy`
and guess what? After `npm i` I got v1.0.0...
So option B is out...
Honestly I would go with option A, so people using that one with their v14 code would be able to upgrade without changing the import (being the same `NgxMatTimepickerModule`)...
I'll setup the new repo on the 26th...
Merry Christmas!

**Comment by LayZeeDK** [comment]
We are using Timepicker v15 with the legacy form field control.

**Comment by tonysamperi** [comment]
Then I declare this thread officially closed.

Cheers

**Comment by LayZeeDK** [comment]
Yes, I had to write a few styles to override Timepicker styles but I'm uncertain if this was due to our custom styles or legacy Angular Material styles.

**Comment by tonysamperi** [comment]
> 

Technically you shouldn't see any differences if you use this lib inside a legacy project. 
In fact the dialog and buttons appearance should be identical.
So unless you changed one or the other, yes, it's your custom styles

**Comment by LayZeeDK** [comment]
We have both sets of styles to transition incrementally.

**Pull request merged**
