### PR TITLE
Migrated the project to Angular 12

### PR DESCRIPTION
**Pull request by jpleclerc**

### CODE REVIEW

**Comment by tonysamperi** [comment]
You made a lot of unnecessary changes, plus you don't have to delete the package.lock.
I'll take care of the update next week.

**Comment by jpleclerc** [comment]
Its the product of "ng update @angular/cli @angular/core @angular/material"

**Comment by tonysamperi** [comment]
That's why I don't do automated updates. I'll use the versions in your package.json as reference for updating.
But all the other changes (especially the ones on the styles) are useless.
Give me a few days and I'll take care myself. 
Thanks anyway.

**Comment by tonysamperi** [comment]
@jpleclerc as promised, we finally have ngx-mat-timepicker@12.0.0!! 🎉

**Pull request closed without merging**
